[connections.postgresql]

# O Streamlit usará a biblioteca 'psycopg2' automaticamente

# host é o endereço do seu servidor PostgreSQL (ex: localhost, ou o IP)
host = "py-postgres"
port = 5432

# Lembre-se de alterar a credencial
database = "postgres"
username = "postgres"
password = "postgres"